# Generated by Django 3.2.2 on 2021-08-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('frontloading', '0001_initial'), ('frontloading', '0002_auto_20210510_1456'), ('frontloading', '0003_document_user'), ('frontloading', '0004_auto_20210510_2106'), ('frontloading', '0005_rename_pronumciation_word_pronunciation'), ('frontloading', '0006_auto_20210514_1705'), ('frontloading', '0007_remove_word_content_reference'), ('frontloading', '0008_auto_20210518_1912'), ('frontloading', '0009_auto_20210518_2002'), ('frontloading', '0010_auto_20210531_1221'), ('frontloading', '0011_rename_image_ref_word_image'), ('frontloading', '0012_auto_20210531_1422'), ('frontloading', '0013_auto_20210601_1117'), ('frontloading', '0014_auto_20210601_1533'), ('frontloading', '0010_alter_word_image'), ('frontloading', '0015_merge_0010_alter_word_image_0014_auto_20210601_1533')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_by', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oauth_ident', models.CharField(max_length=100)),
                ('last_online', models.DateTimeField(verbose_name='date modified')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('example', models.CharField(default=None, max_length=500)),
                ('pronunciation', models.CharField(default=None, max_length=200)),
                ('sentence', models.CharField(default=None, max_length=500)),
                ('synonyms', models.CharField(default=None, max_length=200)),
                ('word_family', models.CharField(default=None, max_length=200)),
                ('definition', models.CharField(max_length=300)),
                ('domains', models.ManyToManyField(to='frontloading.Domain')),
                ('topics', models.ManyToManyField(to='frontloading.Topic')),
                ('type', models.CharField(default='noun', max_length=100)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
                ('etymology', models.CharField(default='', max_length=200)),
                ('parts', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('word1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='word1', to='frontloading.word')),
                ('word2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='word2', to='frontloading.word')),
                ('word3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='word3', to='frontloading.word')),
                ('word4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='word4', to='frontloading.word')),
                ('word5', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='word5', to='frontloading.word')),
                ('title', models.CharField(default=None, max_length=200)),
                ('domains', models.ManyToManyField(to='frontloading.Domain')),
                ('topics', models.ManyToManyField(to='frontloading.Topic')),
            ],
        ),
    ]
