# Generated by Django 3.2.2 on 2021-05-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0002_auto_20210510_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oauth_ident', models.CharField(max_length=100)),
                ('last_online', models.DateTimeField(verbose_name='date modified')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.CharField(max_length=200)),
                ('topics', models.CharField(max_length=200)),
                ('subjects', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('word1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word1', to='frontloading.definition')),
                ('word2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word2', to='frontloading.definition')),
                ('word3', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word3', to='frontloading.definition')),
                ('word4', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word4', to='frontloading.definition')),
                ('word5', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word5', to='frontloading.definition')),
            ],
        ),
    ]
