# Generated by Django 3.2.2 on 2021-05-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0004_auto_20210510_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='pronumciation',
            new_name='pronunciation',
        ),
    ]
