# Generated by Django 3.2.2 on 2021-05-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0005_rename_pronumciation_word_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='type',
            field=models.CharField(default='noun', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(max_length=300),
        ),
    ]
