# Generated by Django 3.2.2 on 2021-05-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0006_auto_20210514_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='content_reference',
        ),
    ]
