# Generated by Django 3.2.2 on 2021-05-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0007_remove_word_content_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='word',
            name='subjects',
        ),
    ]
