# Generated by Django 3.2.2 on 2021-05-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0008_auto_20210518_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='word1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word1', to='frontloading.word'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word2', to='frontloading.word'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word3', to='frontloading.word'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word4', to='frontloading.word'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='word5', to='frontloading.word'),
        ),
    ]
