# Generated by Django 3.2.2 on 2021-05-31 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0009_auto_20210518_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('upload_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
        migrations.AddField(
            model_name='word',
            name='image_ref',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontloading.picture'),
        ),
    ]
