# Generated by Django 3.2.2 on 2021-05-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0009_auto_20210518_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
