# Generated by Django 3.2.2 on 2021-05-31 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0010_auto_20210531_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='image_ref',
            new_name='image',
        ),
    ]
