# Generated by Django 3.2.2 on 2021-06-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0010_alter_word_image'),
        ('frontloading', '0014_auto_20210601_1533'),
    ]

    operations = [
    ]
