# Generated by Django 3.2.2 on 2021-08-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontloading', '0001_squashed_0015_merge_0010_alter_word_image_0014_auto_20210601_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('disciplinary_year7', models.CharField(max_length=500)),
                ('disciplinary_year8', models.CharField(max_length=500)),
                ('disciplinary_year9', models.CharField(max_length=500)),
                ('disciplinary_year10', models.CharField(max_length=500)),
                ('task_year7', models.CharField(max_length=200)),
                ('task_year8', models.CharField(max_length=200)),
                ('task_year9', models.CharField(max_length=200)),
                ('task_year10', models.CharField(max_length=200)),
                ('academic_vocab', models.CharField(max_length=600)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('domains', models.ManyToManyField(to='frontloading.Domain')),
            ],
        ),
    ]
